name: revalidate-story
description: "Clear checkboxes and re-verify story against actual codebase implementation. Identifies gaps and optionally fills them."
author: "Jonah Schulte (leveraging BMAD Method)"

# Critical variables from config
config_source: "{project-root}/_bmad/pantheon/config.yaml"
output_folder: "{project-root}/_bmad-output"
sprint_artifacts: "{output_folder}/sprint-artifacts"

# Workflow paths
installed_path: "{project-root}/_bmad/pantheon/workflows/revalidate-story"
instructions: "{installed_path}/workflow.md"

# Input parameters
story_file: "{story_file}" # Required: Full path to story file
fill_gaps: false # Optional: Fill missing items after verification (default: verify-only)
auto_commit: false # Optional: Auto-commit filled gaps (default: prompt)

# Verification settings
verification:
  verify_acceptance_criteria: true
  verify_tasks: true
  verify_definition_of_done: true
  check_for_stubs: true # Reject stub implementations (TODO, Not implemented, etc.)
  require_tests: true # Require tests for code items

# Gap filling settings (only used if fill_gaps=true)
gap_filling:
  max_gaps_to_fill: 10 # Safety limit - HALT if more gaps than this
  require_confirmation: true # Ask before filling each gap (false = auto-fill all)
  run_tests_after_each: true # Verify each filled gap works
  commit_strategy: "per_gap" # "per_gap" | "all_at_once" | "none"

# Output settings
output:
  create_report: true # Generate revalidation-report.md
  update_dev_agent_record: true # Add revalidation notes to story
  update_sprint_status: true # Update progress in sprint-status.yaml

standalone: false
web_bundle: false
