name: validate
description: "Unified validation workflow. Validates stories against codebase, detects false positives, reports health scores. Replaces validate-story, validate-story-deep, validate-all-stories, validate-all-stories-deep, validate-epic-status, validate-all-epics."
author: "Jonah Schulte (leveraging BMAD Method)"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
implementation_artifacts: "{config_source}:implementation_artifacts"
story_dir: "{implementation_artifacts}"
sprint_status: "{implementation_artifacts}/sprint-status.yaml"

# Workflow components
installed_path: "{project-root}/_pantheon/workflows/validate"
instructions: "{installed_path}/workflow.md"

# Input variables
variables:
  scope: "story" # story | epic | all
  target: "" # story_file path OR epic_number (depends on scope)
  depth: "quick" # quick | deep (deep uses Haiku agents)
  fix_mode: false # If true, auto-fix false negatives and update statuses

# Deep validation settings
deep_validation:
  model: "haiku"
  batch_size: 10
  cost_per_story: 0.13

# Output
default_output_file: "{story_dir}/.validation-{scope}-{date}.md"

standalone: true
web_bundle: false
