name: story-closer
description: "Lightweight batch story closer — scans ALL stories for unchecked tasks (ignoring sprint-status), autonomously executes remaining work, reviews quality, and updates artifacts. Routes stories >30% unchecked to full story-pipeline."
author: "Jonah Schulte (leveraging BMAD Method)"

# Critical variables from config
config_source: "{project-root}/_bmad/pantheon/config.yaml"
output_folder: "{project-root}/_bmad-output"
communication_language: "{config_source}:communication_language"
date: system-generated

# Sprint artifacts
sprint_artifacts: "{output_folder}/sprint-artifacts"

# Workflow paths
installed_path: "{project-root}/_bmad/pantheon/workflows/story-closer"
instructions: "{installed_path}/workflow.md"
agents_path: "{installed_path}/agents"

# Triage configuration
triage:
  closeable_threshold: 0.30  # <=30% unchecked -> story-closer handles
  clean_threshold: 0         # 0 unchecked -> skip (already done)
  needs_pipeline: ">30%"     # >30% unchecked -> route to full story-pipeline

# Review configuration
review:
  mode: consolidated         # Single Multi-Reviewer agent per story
  perspectives: [Argus, Nemesis, Cerberus, Hestia]
  max_fix_iterations: 2

# Issue classification
issue_classification:
  MUST_FIX: "Blocks completion - security, correctness, tests fail"
  SHOULD_FIX: "Real issue but non-blocking - edge cases, minor bugs"
  STYLE: "Preference only - naming, formatting, alternative approaches"

# Human validation patterns (tasks matching these are skipped and reported)
human_validation_patterns:
  - "manually verify"
  - "manual test"
  - "QA sign-off"
  - "user acceptance"
  - "visually confirm"
  - "browser test"
  - "human review"

# Agent configuration
agents:
  teleos:
    description: "Per-story closer worker — execute remaining tasks, review, reconcile, commit"
    subagent_type: "general-purpose"
    model: "opus"
    prompt_file: "{agents_path}/closer-worker.md"
    fresh_context: true
    trust_level: "high"
    timeout: 3600  # 1 hour per story

  multi_reviewer:
    description: "Consolidated 4-perspective review (Argus+Nemesis+Cerberus+Hestia)"
    subagent_type: "general-purpose"
    model: "sonnet"
    fresh_context: true
    timeout: 600  # 10 minutes

# Execution settings
execution:
  modes: ["sequential", "parallel"]
  parallel_wave_sizes:
    small: { max_stories: 5, wave_size: 5 }    # All at once
    medium: { max_stories: 15, wave_size: 5 }   # Waves of 5
    large: { min_stories: 16, wave_size: 8 }    # Waves of 8

# Sprint status update thresholds
sprint_status_thresholds:
  done: 0.95       # >=95% checked and no blocked tasks
  review: 0.80     # >=80% checked
  in_progress: 0   # Below 80%

# Related workflows
related:
  story_pipeline: "{project-root}/_bmad/pantheon/workflows/story-pipeline"

standalone: true
