name: batch-stories
description: "Interactive batch selector for story-pipeline with complexity-based routing, smart wave ordering, and comprehensive session reporting."
author: "Jonah Schulte (leveraging BMAD Method)"
version: "4.0.0"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
sprint_artifacts: "{config_source}:sprint_artifacts"
communication_language: "{config_source}:communication_language"
date: system-generated

# Workflow paths
installed_path: "{project-root}/_pantheon/workflows/batch-stories"
instructions: "{installed_path}/workflow.md"

# State management
sprint_status: "{sprint_artifacts}/sprint-status.yaml"
batch_log: "{sprint_artifacts}/batch-stories-{date}.log"

# Variables
filter_by_epic: "" # Optional: Filter stories by epic number (e.g., "3" for only Epic 3 stories)
max_stories: 20 # Safety limit - won't process more than this in one batch
pause_between_stories: 5 # Seconds to pause between stories (allows monitoring, prevents rate limits)

# Super-dev-pipeline invocation settings
super_dev_settings:
  mode: "batch" # Always use batch mode for autonomous execution
  workflow_path: "{project-root}/_pantheon/workflows/story-pipeline"

# Story validation settings (NEW in v1.2.0)
validation:
  enabled: true # Validate story files before processing
  auto_create_missing: false # If true, auto-create without prompting (use with caution)
  auto_regenerate_invalid: false # If true, auto-regenerate without prompting (use with caution)
  min_sections: 12 # BMAD format requires all 12 sections
  min_current_state_words: 100 # Current State must have substantial content
  require_gap_analysis: true # Current State must have ✅/❌ markers
  backup_before_regenerate: true # Create .backup file before regenerating

# Story complexity scoring (NEW in v1.3.0)
# Routes stories to appropriate pipeline based on complexity
complexity:
  enabled: true
  thresholds:
    micro: # Lightweight path: skip gap analysis + code review
      max_tasks: 3
      max_files: 5
      risk_keywords: [] # No high-risk keywords allowed
    standard: # Normal path: full pipeline
      max_tasks: 15
      max_files: 30
      risk_keywords: ["api", "service", "component", "feature"]
    complex: # Enhanced path: extra validation, consider splitting
      min_tasks: 16
      risk_keywords: ["auth", "security", "migration", "database", "payment", "encryption"]

  # Risk keyword scoring (adds to complexity)
  risk_weights:
    high: ["auth", "security", "payment", "encryption", "migration", "database", "schema"]
    medium: ["api", "integration", "external", "third-party", "cache"]
    low: ["ui", "style", "config", "docs", "test"]

  # Keyword matching configuration (defines how risk keywords are detected)
  keyword_matching:
    case_sensitive: false # "AUTH" matches "auth"
    require_word_boundaries: true # "auth" won't match "author"
    match_strategy: "exact" # exact word match required (no stemming)
    scan_locations:
      - story_title
      - task_descriptions
      - subtask_descriptions
    # Keyword variants (synonyms that map to canonical forms)
    variants:
      auth: ["authentication", "authorize", "authorization", "authz", "authn"]
      database: ["db", "databases", "datastore"]
      payment: ["payments", "pay", "billing", "checkout"]
      migration: ["migrations", "migrate"]
      security: ["secure", "security"]
      encryption: ["encrypt", "encrypted", "cipher"]

  # Task counting rules
  task_counting:
    method: "top_level_only" # Only count [ ] at task level, not subtasks
    # Options: "top_level_only", "include_subtasks", "weighted"
    # Example:
    # - [ ] Parent task       <- counts as 1
    #   - [ ] Subtask 1       <- ignored
    #   - [ ] Subtask 2       <- ignored

# Execution settings
execution:
  continue_on_failure: true # Keep processing remaining stories if one fails
  display_progress: true # Show running summary after each story
  save_state: true # Save progress to resume if interrupted

# Session reporting settings (NEW in v1.4.0)
session_reporting:
  enabled: true # Generate comprehensive session report at end
  output_dir: "{sprint_artifacts}/session-reports"
  include_sections:
    - executive_summary      # 2-3 paragraph narrative
    - features_delivered     # Per-story feature descriptions
    - technical_summary      # Files, tests, coverage tables
    - verification_guide     # Manual testing checklist
    - issues_and_debt        # Fixed and deferred issues
    - next_steps             # Follow-up actions
    - detailed_metrics       # Per-story breakdown (appendix)
  report_agent:
    name: "hermes"
    prompt_file: "{installed_path}/agents/session-reporter.md"
    subagent_type: "general-purpose"
    model: "sonnet"

# Agent Teams configuration (NEW in v4.0.0, updated v4.1.0)
# Replaces wave-based parallel execution with TeammateTool swarm coordination.
# EXPERIMENTAL: Requires CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1 environment variable.
# This feature is experimental and may change. See: Claude Code Agent Teams documentation.
swarm_config:
  enabled: true                 # Use TeammateTool swarm for parallel mode
  experimental: true            # Agent Teams is an experimental feature — may change without notice
  team_prefix: "batch"          # Team name: batch-{epic} or batch-{timestamp}
  max_workers: 3                # Number of Heracles worker teammates to spawn
  worker_model: "opus"           # Model for Heracles worker agents (must be opus to orchestrate 7-phase pipeline with sub-agent spawning)
  worker_persona: "{installed_path}/agents/heracles.md"
  delegate_mode: recommended    # Use Shift+Tab delegate mode for the lead so it coordinates without implementing

  # Quality Gate Coordinator (Hygeia) — serializes expensive quality checks across workers
  # Spawns as a team member when max_workers >= 2. Workers message Hygeia for type-check/build
  # instead of running them independently, preventing CPU contention from parallel tsc processes.
  quality_gate:
    enabled: true               # Set false to disable Hygeia (workers run checks independently)
    min_workers_to_spawn: 2     # Only spawn Hygeia when this many workers are active
    agent_model: "sonnet"       # Hygeia just runs bash commands, doesn't need opus
    agent_persona: "{installed_path}/agents/hygeia.md"

  # Agent Teams requires these Claude Code features:
  # - TeammateTool (spawnTeam, cleanup)
  # - SendMessage (inter-agent messaging)
  # - TaskCreate/TaskUpdate/TaskList (shared task list)
  # - Task with team_name param (teammate spawning)
  requires:
    env: CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1  # Must be set before launching Claude Code

standalone: true
